name       : nuvola-app-soundcloud
version    : 1.1
release    : 1
source     :
    - https://github.com/tiliado/nuvola-app-soundcloud/archive/1.1.tar.gz : bab5badce194a86efc747bffe5ddced2cdeb3ffc598cbe4b2017ae93f7de1aec
license    : BSD-2-Clause
component  : desktop.multimedia
summary    : SoundCloud Integration for Nuvola Player 3.
description: |
    Integration of SoundCloud into your linux desktop via Nuvola Player.
builddeps  :
    - librsvg-devel
rundeps    :
    - nuvolaplayer
build      : |
    %make
install    : |
    %make_install DEST="$installdir/usr/share/nuvolaplayer3/web_apps"
